const initialState = {

  company: {
    name: 'My plants',
    logo: 'https://i.postimg.cc/c1MCBrMx/logo2.png',
  },
  news: {
    information1: {
      title: 'The most amazing plants',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      image: 'https://i.postimg.cc/PrT2KXNb/png.png',
    },
    information2: {
      title: 'The best healer in nature',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      image: 'https://i.postimg.cc/7LFNzDp2/pppng.png',
    },
  },
  products: [
    {
      id: '1',
      name: 'Browningia Hertlinglana',
      photo: 'https://i.postimg.cc/x8zWdvpM/1png.png',
      price: 27,
      water: '1/week',
      light: 'low',
      temperature: '20-27 °C',
    },
    {
      id: '2',
      name: 'Calathea Rattlesnake',
      photo: 'https://i.postimg.cc/MK23kWFF/Bez-nazwy-4.png',
      price: 34,
      water: '1/week',
      light: 'medium',
      temperature: '18-25 °C',
    },
    {
      id: '3',
      name: 'Chlorophytum Comosum',
      photo: 'https://i.postimg.cc/TP4QtGbQ/Bez-23.png',
      price: 26,
      water: '2/week',
      light: 'bright',
      temperature: '20-27 °C',
    },
    {
      id: '4',
      name: 'Crassula Ovata',
      photo: 'https://i.postimg.cc/LXgD77BS/Bez-nazwy-3.png',
      price: 78,
      water: '2/week',
      light: 'medium',
      temperature: '20-27 °C',
    },
    {
      id: '5',
      name: 'Dracena Tifasciata',
      photo: 'https://i.postimg.cc/rFkjnfd6/Bez-nazwy-4.png',
      price: 34,
      water: '2/week',
      light: 'bright',
      temperature: '20-27 °C',
    },
    {
      id: '6',
      name: 'Haworthiopsis Attenuata',
      photo: 'https://i.postimg.cc/hP1rHVxX/Bez-nazwy-3.png',
      price: 24,
      water: '1/week',
      light: 'medium',
      temperature: '18-25 °C',
    },
    {
      id: '7',
      name: 'Strelitzia Nicolai',
      photo: 'https://i.postimg.cc/dVW90v5v/Bez-nazwy-5.png',
      price: 33,
      water: '2/week',
      light: 'low',
      temperature: '20-27 °C',
    },
    {
      id: '8',
      name: 'Peperomia Melencia',
      photo: 'https://i.postimg.cc/bNh3xNX8/Bez-nazwy-44.png',
      price: 45,
      water: '3/week',
      light: 'low',
      temperature: '20-27 °C',
    },
  ],
};

export default initialState;
